### ISSUE TITLE
Please kindly help answer : at the first layer how to distinguish low-frequency and high-frequency feature maps

### ISSUE THREAD

**Issue by sjh717** [ThoroughImages/OctConv#2]
Please kindly help answer : at the first layer how to distinguish low-frequency and high-frequency feature maps

**Comment by savourylie** [comment]
You don't have low-frequency feature maps before the first layer. The one-octavte-lower feature maps are created by the OctConv layer as a low-frequency feature extraction method. Any feature maps prior to the first OctConv layer are considered high-frequency.

**Comment by sjh717** [comment]
> 
> 
> You don't have low-frequency feature maps before the first layer. The one-octavte-lower feature maps are created by the OctConv layer as a low-frequency feature extraction method. Any feature maps prior to the first OctConv layer are considered high-frequency.

**Comment by sjh717** [comment]
> 
> 
> You don't have low-frequency feature maps before the first layer. The one-octavte-lower feature maps are created by the OctConv layer as a low-frequency feature extraction method. Any feature maps prior to the first OctConv layer are considered high-frequency.

So,

> 
> 
> You don't have low-frequency feature maps before the first layer. The one-octavte-lower feature maps are created by the OctConv layer as a low-frequency feature extraction method. Any feature maps prior to the first OctConv layer are considered high-frequency.

Thanks for your reply first.Do you mean that the first OctConv randomly selects a certain percentage of input feature maps, reducing their resolution as  low-frequency feature maps?

**Comment by sjh717** [comment]
> You don't have low-frequency feature maps before the first layer. The one-octavte-lower feature maps are created by the OctConv layer as a low-frequency feature extraction method. Any feature maps prior to the first OctConv layer are considered high-frequency.

Thanks for your reply first.Do you mean that the first OctConv randomly selects a certain percentage of input feature maps, reducing their resolution as low-frequency feature maps?

**Comment by savourylie** [comment]
Short answer, no. 

Here's the TL;DR: as is explained in the paper:

> We set α_in = α_out = α throughout the network, apart from the first and last OctConv of the network where α_in = 0, α_out = α and α_in = α, α_out = 0, respectively.

In the paper α_in = α_out = α = 0.5 is set across the whole network, except for the first and the last layers. So to answer your question, all channels are used in the layer to go thru two convolutions separately, one with W_HH as weights and one with W_HL as weights, where the number of the kernels of W_HH are set to (1 - α_out) * c, and W_HL to α_out * c, respectively. 

As a result, the first layer will produce two outputs, the high-frequency feature maps with (1 - α_out) * c channels, and the low-frequency feature maps with α_out * c channels. 

The operation in the last layer is similar just going the other way around.

Hope this helps.
