### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'padding_mode'

### ISSUE THREAD

**Issue by kevinhan2018** [ThoroughImages/OctConv#4]
Thank you for your work that does help me a lot. Here I have one question, if the input of octave convolution network is (batch_size, channels, H, W) where H is equal to 1000, while W is equal to one. Then I use the code `self.convs = nn.Sequential(OctConv2d('first', in_channels=1, out_channels=32, kernel_size=3),`;it raises a TypeError:__init__() missing 1 required positional argument: 'padding_mode' in 
`        super(OctConv2d, self).__init__(
            in_channels, out_channels, kernel_size, stride, padding, dilation,
            False, _pair(0), 1, bias)`
Thank you!

**Comment by wuzhenyubuaa** [comment]
Hey, @kevinhan2018，you can solve this problem by adding the parameter 'padding_mode' in super().__init__() like this:

```
super(OctConv2d, self).__init__(
            in_channels, out_channels, kernel_size, stride, padding, dilation,
            False, _pair(0), 1, bias, padding_mode='zeros')
```

good lucky!

**Comment by kevinhan2018** [comment]
Thanks a lot!
